In [1]:
import pandas as pd

df = pd.read_csv('/Users/pauviramontes/Downloads/Crop_recommendation 2.csv')

In [2]:
df.head(10)

N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice
5  69  37  42    23.058049  83.370118  7.073454  251.055000  rice
6  69  55  38    22.708838  82.639414  5.700806  271.324860  rice
7  94  53  40    20.277744  82.894086  5.718627  241.974195  rice
8  89  54  38    24.515881  83.535216  6.685346  230.446236  rice
9  68  58  38    23.223974  83.033227  6.336254  221.209196  rice

In [3]:
df['label'] = df['label'].astype(str)

In [4]:
df['label'].value_counts()

rice           100
maize          100
jute           100
cotton         100
coconut        100
papaya         100
orange         100
apple          100
muskmelon      100
watermelon     100
grapes         100
mango          100
banana         100
pomegranate    100
lentil         100
blackgram      100
mungbean       100
mothbeans      100
pigeonpeas     100
kidneybeans    100
chickpea       100
coffee         100
Name: label, dtype: int64

In [5]:
df['label'].nunique()

22

In [6]:
df['label'] = df['label'].str.strip()

In [7]:
df['label'] = df['label'].astype(str).str.lower()


# Check number of unique classes in target variable
print("Unique values in target variable:", df['label'].unique())
print("Number of classes:", len(df['label'].unique()))

# Check class distribution
print(df['label'].value_counts())

Unique values in target variable: ['rice' 'maize' 'chickpea' 'kidneybeans' 'pigeonpeas' 'mothbeans'
 'mungbean' 'blackgram' 'lentil' 'pomegranate' 'banana' 'mango' 'grapes'
 'watermelon' 'muskmelon' 'apple' 'orange' 'papaya' 'coconut' 'cotton'
 'jute' 'coffee']
Number of classes: 22
rice           100
maize          100
jute           100
cotton         100
coconut        100
papaya         100
orange         100
apple          100
muskmelon      100
watermelon     100
grapes         100
mango          100
banana         100
pomegranate    100
lentil         100
blackgram      100
mungbean       100
mothbeans      100
pigeonpeas     100
kidneybeans    100
chickpea       100
coffee         100
Name: label, dtype: int64


In [8]:
X = df[['N', 'P', 'K', 'temperature', 'ph', 'rainfall']]

In [9]:
y = df['label']

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()
logreg.fit(X_train, y_train)

/Users/pauviramontes/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [12]:
import numpy as np

unique_values = np.unique(df['label'])
num_classes = len(unique_values)

print("Unique values in target variable:", unique_values)
print("Number of classes:", num_classes)


Unique values in target variable: ['apple' 'banana' 'blackgram' 'chickpea' 'coconut' 'coffee' 'cotton'
 'grapes' 'jute' 'kidneybeans' 'lentil' 'maize' 'mango' 'mothbeans'
 'mungbean' 'muskmelon' 'orange' 'papaya' 'pigeonpeas' 'pomegranate'
 'rice' 'watermelon']
Number of classes: 22


In [13]:
y_pred = logreg.predict(X_test)

In [14]:
print(y_pred)


['muskmelon' 'watermelon' 'papaya' 'papaya' 'apple' 'mango' 'apple'
 'mothbeans' 'mothbeans' 'lentil' 'blackgram' 'coconut' 'pomegranate'
 'jute' 'coconut' 'pomegranate' 'apple' 'cotton' 'papaya' 'muskmelon'
 'coffee' 'papaya' 'orange' 'papaya' 'chickpea' 'jute' 'blackgram'
 'orange' 'kidneybeans' 'rice' 'pomegranate' 'lentil' 'jute' 'lentil'
 'jute' 'blackgram' 'jute' 'chickpea' 'chickpea' 'kidneybeans' 'papaya'
 'mango' 'blackgram' 'maize' 'mungbean' 'blackgram' 'pigeonpeas' 'coconut'
 'muskmelon' 'maize' 'blackgram' 'coffee' 'grapes' 'mungbean' 'coffee'
 'kidneybeans' 'cotton' 'apple' 'banana' 'lentil' 'watermelon' 'coconut'
 'lentil' 'orange' 'papaya' 'blackgram' 'orange' 'rice' 'muskmelon'
 'pigeonpeas' 'muskmelon' 'coconut' 'jute' 'banana' 'blackgram' 'papaya'
 'banana' 'cotton' 'watermelon' 'orange' 'coffee' 'chickpea' 'rice'
 'mothbeans' 'orange' 'mango' 'coffee' 'mothbeans' 'blackgram'
 'pomegranate' 'maize' 'mothbeans' 'cotton' 'papaya' 'pigeonpeas'
 'mothbeans' 'kidneybeans'

In [15]:
import pandas as pd

# create a DataFrame with the test data and the predicted values
results = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})

# display the first 10 rows of the results
print(results.head(10))

          Actual   Predicted
1451   muskmelon   muskmelon
1334  watermelon  watermelon
1761      papaya      papaya
1735      papaya      papaya
1576       apple       apple
1110       mango       mango
1594       apple       apple
530    mothbeans   mothbeans
651     mungbean   mothbeans
819       lentil      lentil


In [16]:
accuracy = logreg.score(X_test, y_test)
print("The model's accuracy is:", accuracy)

The model's accuracy is: 0.8681818181818182


In [17]:
from sklearn.metrics import f1_score

# Assuming y_test and y_pred are the true labels and predicted labels respectively
f1 = f1_score(y_test, y_pred, average='weighted')
print(f"F1 score: {f1:.2f}")


F1 score: 0.87


In [18]:
from sklearn.metrics import classification_report

y_pred = logreg.predict(X_test)
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

       apple       1.00      1.00      1.00        23
      banana       0.95      1.00      0.98        21
   blackgram       0.67      0.80      0.73        20
    chickpea       1.00      1.00      1.00        26
     coconut       1.00      0.93      0.96        27
      coffee       0.89      0.94      0.91        17
      cotton       0.80      0.94      0.86        17
      grapes       1.00      1.00      1.00        14
        jute       0.91      0.87      0.89        23
 kidneybeans       0.72      0.65      0.68        20
      lentil       0.61      1.00      0.76        11
       maize       0.94      0.71      0.81        21
       mango       0.95      1.00      0.97        19
   mothbeans       0.64      0.38      0.47        24
    mungbean       0.50      0.63      0.56        19
   muskmelon       1.00      1.00      1.00        17
      orange       0.93      1.00      0.97        14
      papaya       0.88    

In [19]:
from sklearn.metrics import confusion_matrix

# Generate confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix:")
print(cm)


Confusion matrix:
[[23  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 16  0  0  0  0  0  0  0  2  0  0  1  1  0  0  0  0  0  0  0]
 [ 0  0  0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  1  1  0  0  0  0]
 [ 0  0  0  0  0 16  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 16  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 14  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  0 20  0  0  0  0  0  0  0  0  1  0  0  1  0]
 [ 0  0  1  0  0  0  0  0  0 13  2  0  0  0  0  0  0  0  4  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 11  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  1  0  0  0  4  0  0  0  0 15  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 19  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  0  0  0  0  0  0  0  2  0  0  9 11  0  0  0  0  0  0  0]
 [ 0  0  3  0  0

In [25]:
import pickle

# Save model to file
with open('LR.pickle', 'wb') as f:
    pickle.dump(logreg, f)


In [27]:
# Load model from file
with open('LR.pickle', 'rb') as f:
    logreg = pickle.load(f)


In [28]:
import pickle

# Load the saved model
with open('LR.pickle', 'rb') as f:
    loaded_model = pickle.load(f)

# Use the loaded model to make predictions
y_pred = loaded_model.predict(X_test)

# Print the predictions
print(y_pred)


['muskmelon' 'watermelon' 'papaya' 'papaya' 'apple' 'mango' 'apple'
 'mothbeans' 'mothbeans' 'lentil' 'blackgram' 'coconut' 'pomegranate'
 'jute' 'coconut' 'pomegranate' 'apple' 'cotton' 'papaya' 'muskmelon'
 'coffee' 'papaya' 'orange' 'papaya' 'chickpea' 'jute' 'blackgram'
 'orange' 'kidneybeans' 'rice' 'pomegranate' 'lentil' 'jute' 'lentil'
 'jute' 'blackgram' 'jute' 'chickpea' 'chickpea' 'kidneybeans' 'papaya'
 'mango' 'blackgram' 'maize' 'mungbean' 'blackgram' 'pigeonpeas' 'coconut'
 'muskmelon' 'maize' 'blackgram' 'coffee' 'grapes' 'mungbean' 'coffee'
 'kidneybeans' 'cotton' 'apple' 'banana' 'lentil' 'watermelon' 'coconut'
 'lentil' 'orange' 'papaya' 'blackgram' 'orange' 'rice' 'muskmelon'
 'pigeonpeas' 'muskmelon' 'coconut' 'jute' 'banana' 'blackgram' 'papaya'
 'banana' 'cotton' 'watermelon' 'orange' 'coffee' 'chickpea' 'rice'
 'mothbeans' 'orange' 'mango' 'coffee' 'mothbeans' 'blackgram'
 'pomegranate' 'maize' 'mothbeans' 'cotton' 'papaya' 'pigeonpeas'
 'mothbeans' 'kidneybeans'